### ISSUE TITLE
DUB Package Manager?

### ISSUE THREAD

**Issue by RobLoach** [poeticAndroid/homegirl#1]
I see Windows binaries are in the repo. Would it be beneficial to adopt DUB package manager to help handle dependency management?
https://code.dlang.org

**Comment by poeticAndroid** [comment]
The project already uses DUB to handle most of the dependencies, but it shouldn't be necessary to run the binaries..

**Comment by poeticAndroid** [comment]
oh, you're referring to the DLLs in the repo..? yea, I guess they shouldn't really be in the repo, only in the releases.. I was just being lazy.. :p
and I don't think DUB has the binaries, only the bindings..

**Comment by RobLoach** [comment]
Very cool! Haven't explored d much. I'm getting the following error when trying to run `dub build`...

```
➜  homegirl git:(master) ✗ dub build       
Failed to load package in /home/rob/.dub/packages/riverd-loader-1.0.2/riverd-loader/: BuildOption does not have a member named 'betterC'
Failed to load package in /home/rob/.dub/packages/riverd-loader-1.0.2/riverd-loader/: BuildOption does not have a member named 'betterC'
Failed to load package in /home/rob/.dub/packages/riverd-loader-1.0.2/riverd-loader/: BuildOption does not have a member named 'betterC'
Package riverd-loader 1.0.2 could not be loaded either locally, or from the configured package registries.
Fetching riverd-loader 1.0.2 (getting selected version)...
Failed to load package in /home/rob/.dub/packages/riverd-loader-1.0.2/riverd-loader/: BuildOption does not have a member named 'betterC'
Failed to load package in /home/rob/.dub/packages/riverd-loader-1.0.2/riverd-loader/: BuildOption does not have a member named 'betterC'
Package riverd-loader 1.0.2 could not be loaded either locally, or from the configured package registries.
Package riverd-loader ~master could not be loaded either locally, or from the configured package registries.
Package riverd-loader ~wip-documentation could not be loaded either locally, or from the configured package registries.
Root package homegirl references unknown package riverd-loader
```

**Comment by poeticAndroid** [comment]
what version of `dmd` and `dub` are you using? I installed the latest version from https://dlang.org/ when compiling under Linux..

    $ dmd --version
    DMD64 D Compiler v2.086.0
    Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
    $ dub --version
    DUB version 1.15.0, built on May  4 2019

**Comment by RobLoach** [comment]
Ah, I'm on a REALLY old version... DUB version 1.8.0-2

I'll update it and try again.
